version: '3.7'

services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge