# Generated by Django 4.2.16 on 2025-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
